services:
  postgres:
    image: postgres:13
    container_name: postgres_123
    environment:
      POSTGRES_USER: postgres_1
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"